### ISSUE TITLE
Problem with correct dimensions when switching regressor

### ISSUE THREAD

**Issue by paulgrassler** [ubc-vision/joint-regressor-refinement#13]
Hey, got a quick question and thought you could maybe help me. When switching the standard joint regressor for the one you provided (for H3.6M) does this not cause problems in the forward pass of SMPL since the original regressor was built to output 24 joints while the H3.6M regressor only finds 17 joints. How do you properly switch those two without messing up the dimensions in the forward pass? As you may have guessed, I am not well versed in this area and hope you can forgive me if the answer is obvious and this perchance is a problem caused by some obvious oversight on my part. Thanks in advance!

**Comment by ehedlin** [comment]
the joints returned by 
```
pred_vertices = smpl(global_orient=orient, body_pose=pose,
                         betas=shape, pose2rot=False).joints
```
are not the joints that common methods use to evaluate human3.6m. The regressor in this project is using the same one as in [SPIN](https://github.com/nkolot/SPIN/blob/1e7d8ff4cb0705cf04211760c875098da553c1f8/config.py#L58C11-L58C11)
